project:
  type: website
  resources:
  - images/**
  pre-render:
  - scripts/copy_part01_pics.py

website:
  title: "Hello World devconf 2025"
  search: false
  navbar:
    left:
    - href: index.qmd
      text: Home
    - href: quarto_tools_install.qmd
      text: Quarto工具安裝

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
