project:
  type: website

website:
  title: "Hello World devconf 2025"
  search: false
  navbar:
    left:
    - href: index.qmd
      text: Home

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
